### ISSUE TITLE
Load PXELinux menu 是空的嘛？

### ISSUE THREAD

**Issue by a22124497** [zwj4031/ipxeboot#1]
用tiny pxe  启ubuntu 20用的是 grubnetx64.efi.signed改名成pxeLinux.0
tiny好像直接就是没生效，还是走的他自己的那个ipxe.pxe

如果用tftp32，他就直接是生效了的好像，然后自动调用grub/grub.cfg 下的内容来
    linux /vmlinuz ip=dhcp url=http://192.168.147.1/tftp/ubuntu-20.10-live-server-amd64.iso autoinstall ds=nocloud-net\;s=http://192.168.147.1/tftp/
    echo "Loading Ram Disk..."
    initrd /initrd
————————————————————————
tiny启这个改名后的pxelinux.0,没有用
求问一要怎么修改弄

**Comment by a22124497** [comment]
#更换启动文件
:msboot 
  chain tftp://${next-server}/pxelinux.0
  goto start


网上看到一个这请语句，没用的起来

**Comment by zwj4031** [comment]
tinypxe有些奇怪的问题，一般要改配置，要先删除config.ini，重启电脑。。。再改
